version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/app
      - ./docker/php/logs:/app/var/logs:rw

  db:
    image: mariadb:10.11.3
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: symfony_vat_calculator
    volumes:
      - ./docker/db/config:/etc/mysql/conf.d:ro
      - ./docker/db/data/:/var/lib/mysql:rw
      - ./docker/db/log/:/var/log/mysql:rw

  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - app
